### ISSUE TITLE
errors when running autocraft

### ISSUE THREAD

**Issue by kittenvr** [finiteCraft/finiteCraft#1]
![image](https://github.com/FiniteCraft/finiteCraft/assets/103120356/c7bf9f51-3592-48ab-a6e5-51a3292b0561)
C:\Users\PizzaV\Downloads\finiteCraft-master>pip install -r requirements.txt
Requirement already satisfied: js2py in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (0.74)
Requirement already satisfied: requests in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: pysocks in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (1.7.1)
Requirement already satisfied: fake-useragent in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (1.5.1)
Requirement already satisfied: beautifulsoup4 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (4.11.1)
Requirement already satisfied: ndg-httpsclient in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (0.5.1)
Requirement already satisfied: pyopenssl in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 7)) (24.1.0)
Requirement already satisfied: pyasn1 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (0.4.8)
Requirement already satisfied: pymongo in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (4.6.2)
Requirement already satisfied: gitpython in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 10)) (3.1.42)
Requirement already satisfied: tzlocal>=1.2 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from js2py->-r requirements.txt (line 1)) (5.2)
Requirement already satisfied: six>=1.10 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from js2py->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: pyjsparser>=2.5.1 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from js2py->-r requirements.txt (line 1)) (2.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 2)) (3.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: soupsieve>1.2 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->-r requirements.txt (line 5)) (2.3.2.post1)
Requirement already satisfied: cryptography<43,>=41.0.5 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from pyopenssl->-r requirements.txt (line 7)) (41.0.7)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from pymongo->-r requirements.txt (line 9)) (2.6.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from gitpython->-r requirements.txt (line 10)) (4.0.11)
Requirement already satisfied: cffi>=1.12 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from cryptography<43,>=41.0.5->pyopenssl->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from gitdb<5,>=4.0.1->gitpython->-r requirements.txt (line 10)) (5.0.1)
Requirement already satisfied: tzdata in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from tzlocal>=1.2->js2py->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: pycparser in c:\users\benga\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.12->cryptography<43,>=41.0.5->pyopenssl->-r requirements.txt (line 7)) (2.21)

C:\Users\PizzaV\Downloads\finiteCraft-master>python crafterauto.py
Traceback (most recent call last):
  File "C:\Users\PizzaV\Downloads\finiteCraft-master\crafterauto.py", line 8, in <module>
    import librarian
  File "C:\Users\PizzaV\Downloads\finiteCraft-master\librarian.py", line 11, in <module>
    REPO = Repo(f"{LOCAL_DB_PATH}/.git")
  File "C:\Users\benga\AppData\Local\Programs\Python\Python310\lib\site-packages\git\repo\base.py", line 224, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: C:\Users\PizzaV\Downloads\api\.git

**Comment by quantumbagel** [comment]
Hi!

Sorry about that, autocrafter is designed with two prerequisites:
You need to create another repository with push allowances on GitHub and put it in the same folder as FiniteCraft, like so (This is the cause of the error you are getting):
![image](https://github.com/FiniteCraft/finiteCraft/assets/58365715/0acf64c2-e1de-4557-83a8-91c2ebd54322)
You need to edit librarian.py's line 11 to `DB_URL = "https://raw.githubusercontent.com/<username>/api/master/"`

Let me know how that goes.

**Comment by kittenvr** [comment]
> Hi!
> 
> Sorry about that, autocrafter is designed with two prerequisites: You need to create another repository with push allowances on GitHub and put it in the same folder as FiniteCraft, like so (This is the cause of the error you are getting): ![image](https://private-user-images.githubusercontent.com/58365715/316015190-0acf64c2-e1de-4557-83a8-91c2ebd54322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTI3NzUsIm5iZiI6MTcxMTExMjQ3NSwicGF0aCI6Ii81ODM2NTcxNS8zMTYwMTUxOTAtMGFjZjY0YzItZTFkZS00NTU3LTgzYTgtOTFjMmViZDU0MzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEzMDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ODQ5ZDU3NTRhMmEyMDc2YTgxZWZmOWNkOTQ5MTUxYTAzYTJmODg4MDNhMWY4OTQ2NzM1OTU3NjkyMTM4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_U28VoEsV0YUNhivopB6HELPORJxOWVaFXn1gsYY0E) You need to edit librarian.py's line 11 to `DB_URL = "https://raw.githubusercontent.com/<username>/api/master/"`
> 
> Let me know how that goes.

like to my username?

**Comment by quantumbagel** [comment]
Yes. Please make sure that you actually create the repository api under your account first.

**Comment by kittenvr** [comment]
> Yes. Please make sure that you actually create the repository api under your account first.

repo api?

**Comment by quantumbagel** [comment]
Yes, create a repository named “api”Sent from my Apple WatchOn Mar 22, 2024, at 9:59 AM, PizzaV ***@***.***> wrote:

Yes. Please make sure that you actually create the repository api under your account first.

repo api?

**Comment by quantumbagel** [comment]
I haven't heard back about this issue, so I'm assuming either it's resolved or you are no longer trying to get finiteCraft to run. I'm closing the issue, but if you have any questions, I'd love to help.

**Comment by kittenvr** [comment]
> I haven't heard back about this issue, so I'm assuming either it's resolved or you are no longer trying to get finiteCraft to run. I'm closing the issue, but if you have any questions, I'd love to help.

no idk how to make repo api

**Comment by quantumbagel** [comment]
When finiteCraft v1 is released, I will write a setup guide for the finiteCraft backend and website. Until then, please look up tutorials on how to create GitHub repositories and link them to local Git repositories.

**Comment by PizzaGod873** [comment]
I hate to bother you but my username is also pizza
